#服务器配置
server:
  port: 8088
  servlet:
    context-path: /demo

spring:
  #配置网页
  thymeleaf:
    cache: false

  #配置数据源信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_authdb?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
    #配置全局类型别名
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.luke.mybatisplus.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志配置
logging:
  level:
    com.luke.mybatisplus.mapper: trace

