spring:
  #配置网页
  thymeleaf:
    cache: false

  #配置数据源信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
    #配置全局类型别名
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.luke.mybatisplus.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
